name: Setup environment and dependencies

runs:
  using: "composite"

  steps:
    - name: Setup environment
      uses: ./.github/actions/environment
    - name: Install playwright browsers
      uses: ./.github/actions/playwright
