name: Setup environment

runs:
  using: "composite"

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8.x
        run_install: false

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
