name: Install playwright

runs:
  using: "composite"

  steps:
    - name: Store Playwright's Version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(pnpm ls @playwright/test --depth 0 | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache playwright browsers per version
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

    - name: Setup playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      shell: bash
      run: npx playwright install --with-deps